FileVersion = 1
Dependencies = {corlib = "*", corlib = "*"}

[Project]
Name = "FreeType"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\dist\\win64d\\freetyped.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/win64d/*.dll\")"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\dist\\win64\\freetype.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/win64/*.dll\")"]
